# Generated by Django 4.2.13 on 2024-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="phone",
            new_name="phone_no",
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
