# Generated by Django 4.2.13 on 2024-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=50)),
                ("joindate", models.DateField()),
                ("image", models.BinaryField()),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
    ]
