# Generated by Django 4.2.13 on 2024-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breach",
            fields=[
                ("breach_id", models.AutoField(primary_key=True, serialize=False)),
                ("breach_time", models.DateTimeField()),
                ("image", models.ImageField(upload_to="breach_images/")),
            ],
        ),
    ]
