# Generated by Django 5.0.2 on 2024-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breach',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='breach',
            table='breaches',
        ),
    ]
