# Generated by Django 4.2.13 on 2024-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=50)),
                ("joindate", models.DateField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="employees/"),
                ),
            ],
        ),
    ]
