# Generated by Django 4.2.13 on 2024-06-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("update_emp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"managed": False},
        ),
    ]
