# Generated by Django 5.0.2 on 2024-06-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attended', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attended',
            options={'managed': False},
        ),
    ]
