# Generated by Django 4.2.13 on 2024-06-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=100)),
                ("joindate", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attended",
            fields=[
                ("attended_id", models.AutoField(primary_key=True, serialize=False)),
                ("attendedtime", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance_images/"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notattended.employee",
                    ),
                ),
            ],
        ),
    ]
